[package]
name = "sagex-archive"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
walkdir = "2.5.0"
sagex-capsule = { path = "../sagex-capsule" }
sagex-crypto = { path = "../sagex-crypto" }
sagex-keys = { path = "../sagex-keys" }
promptuity = "0.0.5"
postcard = { version = "1.1.3", features = ["alloc"] }
crc32fast = "1.5.2"
flate2 = "1.1.10"
