use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Static, file-based cluster membership. Arbitrary node ids / addresses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PeerEntry {
    pub id: u64,
    pub addr: String,
    /// Base64 ML-DSA-65 public key (raw bytes).
    #[serde(default)]
    pub pubkey: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeConfig {
    pub node: NodeSection,
    #[serde(default)]
    pub peers: Vec<PeerEntry>,
    #[serde(default)]
    pub consensus: ConsensusSection,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeSection {
    pub id: u64,
    pub listen: String,
    #[serde(default = "default_db")]
    pub db: String,
    /// Base64 ML-DSA-65 secret key (raw bytes). Generated by `init`.
    #[serde(default)]
    pub secret_key: String,
    /// Base64 ML-DSA-65 public key (raw bytes).
    #[serde(default)]
    pub pubkey: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConsensusSection {
    /// Number of tolerated Byzantine faults. Quorum = 2f+1.
    #[serde(default = "default_f")]
    pub f: u64,
    #[serde(default = "default_timeout")]
    pub view_timeout_ms: u64,
}

impl Default for ConsensusSection {
    fn default() -> Self {
        Self {
            f: default_f(),
            view_timeout_ms: default_timeout(),
        }
    }
}

fn default_db() -> String {
    "ledger.db".into()
}
fn default_f() -> u64 {
    1
}
fn default_timeout() -> u64 {
    8000
}

impl NodeConfig {
    pub fn from_file(path: &str) -> anyhow::Result<Self> {
        let text = std::fs::read_to_string(path)?;
        let cfg: Self = toml::from_str(&text)?;
        cfg.validate()?;
        Ok(cfg)
    }

    pub fn validate(&self) -> anyhow::Result<()> {
        if self.peers.iter().any(|p| p.id == self.node.id) {
            anyhow::bail!("peers must not contain own node id");
        }
        // f must satisfy N >= 3f+1 where N = peers+1
        let n = self.peers.len() as u64 + 1;
        if n < 3 * self.consensus.f + 1 {
            anyhow::bail!(
                "N={} too small for f={} (need N>=3f+1)",
                n,
                self.consensus.f
            );
        }
        Ok(())
    }

    pub fn quorum(&self) -> usize {
        (2 * self.consensus.f + 1) as usize
    }

    pub fn cluster_size(&self) -> usize {
        self.peers.len() + 1
    }

    pub fn peer_addrs(&self) -> HashMap<u64, String> {
        self.peers.iter().map(|p| (p.id, p.addr.clone())).collect()
    }

    pub fn leader_of(&self, view: u64) -> u64 {
        // Deterministic rotation over sorted ids (supports arbitrary ids).
        let mut ids: Vec<u64> = self.peers.iter().map(|p| p.id).collect();
        ids.push(self.node.id);
        ids.sort_unstable();
        ids[(view as usize) % ids.len()]
    }
}
