//! Demo conversation seed.

use super::model::{
    Chat, ChatKind, LinkPreview, Message, MessageKind, MessageStatus, extract_link,
};

fn msg(
    id: usize,
    sender: &str,
    text: &str,
    time: &str,
    mine: bool,
    date: &str,
    ticks: MessageStatus,
) -> Message {
    Message {
        id,
        sender: sender.to_string(),
        link: extract_link(text),
        text: text.to_string(),
        time: time.to_string(),
        mine,
        date: date.to_string(),
        kind: MessageKind::Text,
        reactions: vec![],
        deleted: false,
        ticks,
        server_id: None,
    }
}

#[allow(clippy::too_many_arguments)]
fn link_msg(
    id: usize,
    sender: &str,
    text: &str,
    time: &str,
    mine: bool,
    date: &str,
    domain: &str,
    title: &str,
    url: &str,
    ticks: MessageStatus,
) -> Message {
    Message {
        id,
        sender: sender.to_string(),
        text: text.to_string(),
        time: time.to_string(),
        mine,
        date: date.to_string(),
        kind: MessageKind::Text,
        reactions: vec![],
        deleted: false,
        ticks,
        server_id: None,
        link: Some(LinkPreview {
            domain: domain.to_string(),
            title: title.to_string(),
            url: url.to_string(),
        }),
    }
}

pub fn seed_chats() -> Vec<Chat> {
    vec![
        Chat {
            id: 1,
            name: "Design Team".to_string(),
            subtitle: "Ava, Ben, Cara, Dan +3".to_string(),
            kind: ChatKind::Group,
            initials: "DT".to_string(),
            color: 0x0e7c61,
            unread: 3,
            fav: true,
            archived: false,
            chat_pinned: false,
            server_id: None,
            last_time: "9:41 am".to_string(),
            messages: vec![
                msg(
                    1,
                    "Ava",
                    "Morning! Final mockups are up 🎨",
                    "Yesterday",
                    false,
                    "Yesterday",
                    MessageStatus::Sent,
                ),
                msg(
                    2,
                    "Ben",
                    "Reviewed — nav spacing looks off on mobile",
                    "Yesterday",
                    false,
                    "Yesterday",
                    MessageStatus::Sent,
                ),
                msg(
                    3,
                    "You",
                    "Fixing it now, will push in an hour",
                    "9:41 am",
                    true,
                    "Today",
                    MessageStatus::Sent,
                ),
            ],
        },
        Chat {
            id: 2,
            name: "Arjun Mehta".to_string(),
            subtitle: "online".to_string(),
            kind: ChatKind::Dm,
            initials: "AM".to_string(),
            color: 0x54656f,
            unread: 1,
            fav: false,
            archived: false,
            chat_pinned: false,
            server_id: None,
            last_time: "8:15 am".to_string(),
            messages: vec![
                msg(
                    1,
                    "Arjun Mehta",
                    "Did you see the release notes?",
                    "Yesterday",
                    false,
                    "Yesterday",
                    MessageStatus::Sent,
                ),
                msg(
                    2,
                    "Arjun Mehta",
                    "Call at 10? Need 5 mins",
                    "8:15 am",
                    false,
                    "Today",
                    MessageStatus::Sent,
                ),
            ],
        },
        Chat {
            id: 3,
            name: "Family Group".to_string(),
            subtitle: "Mom, Dad, Sis, You".to_string(),
            kind: ChatKind::Group,
            initials: "FG".to_string(),
            color: 0x7f5af0,
            unread: 0,
            fav: true,
            archived: false,
            chat_pinned: false,
            server_id: None,
            last_time: "Yesterday".to_string(),
            messages: vec![
                msg(
                    1,
                    "Mom",
                    "Dinner on Sunday? 🍲",
                    "Yesterday",
                    false,
                    "Yesterday",
                    MessageStatus::Sent,
                ),
                msg(
                    2,
                    "You",
                    "Yes! I'll bring dessert",
                    "Yesterday",
                    true,
                    "Yesterday",
                    MessageStatus::Read,
                ),
            ],
        },
        Chat {
            id: 4,
            name: "Priya Sharma".to_string(),
            subtitle: "last seen recently".to_string(),
            kind: ChatKind::Dm,
            initials: "PS".to_string(),
            color: 0xd3396c,
            unread: 0,
            fav: true,
            archived: false,
            chat_pinned: false,
            server_id: None,
            last_time: "Tuesday".to_string(),
            messages: vec![
                msg(
                    1,
                    "Priya Sharma",
                    "Sending the invoice now 🧾",
                    "Tuesday",
                    false,
                    "Tuesday",
                    MessageStatus::Sent,
                ),
                msg(
                    2,
                    "You",
                    "Got it, thanks!",
                    "Tuesday",
                    true,
                    "Tuesday",
                    MessageStatus::Read,
                ),
            ],
        },
        Chat {
            id: 5,
            name: "Weekend Trekkers".to_string(),
            subtitle: "Ravi,isha, Kabir +12".to_string(),
            kind: ChatKind::Group,
            initials: "WT".to_string(),
            color: 0x1f6feb,
            unread: 5,
            fav: false,
            archived: false,
            chat_pinned: false,
            server_id: None,
            last_time: "7:02 am".to_string(),
            messages: vec![
                msg(
                    1,
                    "Ravi",
                    "Sunday trek — 6am start 🥾",
                    "Yesterday",
                    false,
                    "Yesterday",
                    MessageStatus::Sent,
                ),
                msg(
                    2,
                    "Isha",
                    "I'm in! Bringing snacks",
                    "Yesterday",
                    false,
                    "Yesterday",
                    MessageStatus::Sent,
                ),
                msg(
                    3,
                    "Kabir",
                    "+1, sharing the route map",
                    "7:02 am",
                    false,
                    "Today",
                    MessageStatus::Sent,
                ),
            ],
        },
        Chat {
            id: 6,
            name: "Rohan Iyer".to_string(),
            subtitle: "typing…".to_string(),
            kind: ChatKind::Dm,
            initials: "RI".to_string(),
            color: 0xb3541e,
            unread: 0,
            fav: false,
            archived: false,
            chat_pinned: false,
            server_id: None,
            last_time: "Monday".to_string(),
            messages: vec![
                msg(
                    1,
                    "You",
                    "Happy birthday! 🎉",
                    "Monday",
                    true,
                    "Monday",
                    MessageStatus::Read,
                ),
                msg(
                    2,
                    "Rohan Iyer",
                    "Thank you! 🙏",
                    "Monday",
                    false,
                    "Monday",
                    MessageStatus::Sent,
                ),
            ],
        },
        Chat {
            id: 7,
            name: "Project Phoenix".to_string(),
            subtitle: "Lei, Omar, Zoe, You".to_string(),
            kind: ChatKind::Group,
            initials: "PP".to_string(),
            color: 0x2da44e,
            unread: 0,
            fav: false,
            archived: false,
            chat_pinned: false,
            server_id: None,
            last_time: "12:46 pm".to_string(),
            messages: vec![
                msg(
                    1,
                    "Lei",
                    "Staging deploy is green ✅",
                    "16/9/2026",
                    false,
                    "16/9/2026",
                    MessageStatus::Sent,
                ),
                msg(
                    2,
                    "You",
                    "Great, cutting the release",
                    "16/9/2026",
                    true,
                    "16/9/2026",
                    MessageStatus::Delivered,
                ),
                link_msg(
                    3,
                    "Omar",
                    "https://app.eraser.io/workspace/F4XxRkLlJm9FxSm4EzI?origin=share",
                    "12:46 pm",
                    false,
                    "Today",
                    "app.eraser.io",
                    "app.eraser.io",
                    "https://app.eraser.io/workspace/F4XxRkLlJm9FxSm4EzI?origin=share",
                    MessageStatus::Sent,
                ),
            ],
        },
    ]
}
