/// Every icon in `assets/icons/`. New icon = one variant + one `file()` arm.
// Full catalog: variants wire in as views/routes adopt them.
#[allow(dead_code)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum IconKind {
    Home,
    Chats,
    Threads,
    Files,
    People,
    Settings,
    All,
    Unread,
    Groups,
    Pinned,
    Archived,
    Delete,
    Reply,
    Edit,
    Copy,
    Quote,
    React,
    Pin,
    Forward,
    Link,
    Image,
    File,
    Code,
    Download,
    Upload,
    Attach,
    Data,
    View,
    Open,
    Fullscreen,
    Crop,
    Rotate,
    CopyAs,
    Run,
    Expand,
    Select,
    Video,
    Call,
    Add,
    Search,
    Filter,
    More,
    Mute,
    Check,
    Bold,
    Italic,
    Strike,
    List,
    Number,
    Mention,
    Thread,
    Branch,
    Merge,
    Resolve,
    Unlink,
    Star,
    Flag,
    Info,
    Warning,
    Success,
    Error,
    Moon,
    Sun,
    Monitor,
    Send,
}

impl IconKind {
    pub fn file(self) -> &'static str {
        match self {
            IconKind::Home => "icons/home.svg",
            IconKind::Chats => "icons/chats.svg",
            IconKind::Threads => "icons/threads.svg",
            IconKind::Files => "icons/files.svg",
            IconKind::People => "icons/people.svg",
            IconKind::Settings => "icons/settings.svg",
            IconKind::All => "icons/all.svg",
            IconKind::Unread => "icons/unread.svg",
            IconKind::Groups => "icons/groups.svg",
            IconKind::Pinned => "icons/pinned.svg",
            IconKind::Archived => "icons/archived.svg",
            IconKind::Delete => "icons/delete.svg",
            IconKind::Reply => "icons/reply.svg",
            IconKind::Edit => "icons/edit.svg",
            IconKind::Copy => "icons/copy.svg",
            IconKind::Quote => "icons/quote.svg",
            IconKind::React => "icons/react.svg",
            IconKind::Pin => "icons/pin.svg",
            IconKind::Forward => "icons/forward.svg",
            IconKind::Link => "icons/link.svg",
            IconKind::Image => "icons/image.svg",
            IconKind::File => "icons/file.svg",
            IconKind::Code => "icons/code.svg",
            IconKind::Download => "icons/download.svg",
            IconKind::Upload => "icons/upload.svg",
            IconKind::Attach => "icons/attach.svg",
            IconKind::Data => "icons/data.svg",
            IconKind::View => "icons/view.svg",
            IconKind::Open => "icons/open.svg",
            IconKind::Fullscreen => "icons/fullscreen.svg",
            IconKind::Crop => "icons/crop.svg",
            IconKind::Rotate => "icons/rotate.svg",
            IconKind::CopyAs => "icons/copy_as.svg",
            IconKind::Run => "icons/run.svg",
            IconKind::Expand => "icons/expand.svg",
            IconKind::Select => "icons/select.svg",
            IconKind::Video => "icons/video.svg",
            IconKind::Call => "icons/call.svg",
            IconKind::Add => "icons/add.svg",
            IconKind::Search => "icons/search.svg",
            IconKind::Filter => "icons/filter.svg",
            IconKind::More => "icons/more.svg",
            IconKind::Mute => "icons/mute.svg",
            IconKind::Check => "icons/check.svg",
            IconKind::Bold => "icons/bold.svg",
            IconKind::Italic => "icons/italic.svg",
            IconKind::Strike => "icons/strike.svg",
            IconKind::List => "icons/list.svg",
            IconKind::Number => "icons/number.svg",
            IconKind::Mention => "icons/mention.svg",
            IconKind::Thread => "icons/thread.svg",
            IconKind::Branch => "icons/branch.svg",
            IconKind::Merge => "icons/merge.svg",
            IconKind::Resolve => "icons/resolve.svg",
            IconKind::Unlink => "icons/unlink.svg",
            IconKind::Star => "icons/star.svg",
            IconKind::Flag => "icons/flag.svg",
            IconKind::Info => "icons/info.svg",
            IconKind::Warning => "icons/warning.svg",
            IconKind::Success => "icons/success.svg",
            IconKind::Error => "icons/error.svg",
            IconKind::Moon => "icons/moon.svg",
            IconKind::Sun => "icons/sun.svg",
            IconKind::Monitor => "icons/monitor.svg",
            IconKind::Send => "icons/send.svg",
        }
    }
}
