[package]
name = "sagex-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.11.1"
pbkdf2 = "0.13.0"
sha2 = "0.11.0"
rand = "0.10"
ml-kem = { version = "0.3.2", features = ["getrandom", "zeroize"] }
ml-dsa = { version = "0.1.1", features = ["getrandom", "rand_core", "zeroize"] }
thiserror = "2.0.21"
serde = { version = "1.0.229", features = ["derive"] }
