[package]
name = "sagex-certx"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
mongodb = "3"
sagex-archive = { path = "../sagex-archive" }
sagex-keys = { path = "../sagex-keys" }
tokio = { version = "1.53.2", features = ["macros", "rt-multi-thread", "fs"] }
zeroize = "1"
