#!/usr/bin/env bash
# Generate environments/chatsrv/example-test-set/ (§8 rules):
# fake users/groups/messages + real-shaped keypairs via the keygen CLI.
# Regen ONLY when the user explicitly asks (test-set persists otherwise).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TS="$ROOT/environments/chatsrv/example-test-set"

export CARGO_BUILD_JOBS=1
export CARGO_NET_OFFLINE=true

mkdir -p "$TS/keys"
cargo build -p sagex-keygen
KEYGEN="$ROOT/target/debug/sagex-keygen"

gen_user() {
  local user="$1" pw="$2"
  if [ ! -f "$TS/keys/$user.prv" ]; then
    TEST_PW="$pw" "$KEYGEN" \
      --username "$user" \
      --out-dir "$TS/keys" \
      --no-tpm \
      --password-env TEST_PW
  fi
}

gen_user alice-test alice-test-pw-01
gen_user bob-test bob-test-pw-02
gen_user carol-test carol-test-pw-03

cat > "$TS/users.json" <<'EOF'
[
  {"username": "alice-test", "password": "alice-test-pw-01"},
  {"username": "bob-test", "password": "bob-test-pw-02"},
  {"username": "carol-test", "password": "carol-test-pw-03"}
]
EOF

cat > "$TS/groups.json" <<'EOF'
[
  {"name": "dev-group", "members": ["alice-test", "bob-test", "carol-test"]},
  {"name": "alice-bob", "members": ["alice-test", "bob-test"]}
]
EOF

cat > "$TS/messages.json" <<'EOF'
[
  {"group": "dev-group", "sender": "alice-test", "body": "aGVsbG8gZ3JvdXAgKGVuY3J5cHRlZCk=", "content_type": "text/e2ee"},
  {"group": "dev-group", "sender": "bob-test", "body": "cmVnZXJvIChkZWNyeXB0ZWQp", "content_type": "text/e2ee"},
  {"group": "alice-bob", "sender": "alice-test", "body": "c2VjcmV0IGZvciBib2IgKGVuY3J5cHRlZCk=", "content_type": "text/e2ee", "rustfs_ref": "u/<alice-key>/doc-1.enc"}
]
EOF

cat > "$TS/documents.json" <<'EOF'
[
  {"owner": "alice-test", "filename": "report.enc", "content_type": "application/octet-stream", "note": "client-encrypted; upload via POST /documents/upload-url"}
]
EOF

cat > "$TS/SYNTHETIC" <<'EOF'
SYNTHETIC TEST DATA — NOT REAL USERS.
Generated by scripts/chatsrv-testset.sh for end-to-end exercise of
the sagex-chatsrv compiled-service. Never use against real data.
EOF

cat > "$TS/MANIFEST" <<EOF
generator: scripts/chatsrv-testset.sh
keygen: sagex-keygen (crates2/sagex-keygen, --no-tpm, KDM=password)
users: alice-test, bob-test, carol-test (passwords in users.json)
keys: keys/<user>.prv/.pub (+.seal absent: --no-tpm path)
note: key material is fresh per generation (OS RNG); fixtures otherwise fixed.
regen policy: ONLY on explicit user order (§8 Rule 3).
EOF

echo "test-set ready at $TS"
echo "seed it with: sagex-chatsrv --config environments/chatsrv/config.toml --seed $TS"
