#!/usr/bin/env bash
# Load-test the chatsrv compiled-service with N fake desktop users.
#
# - creates environments/app-instances/desk-test-NNN/ (ready homes:
#   config.toml + state.json + SYNTHETIC marker; launch one with
#   SAGEX_HOME=<dir> target/debug/sagex-desk)
# - registers users via curl, builds groups, posts + verifies messages
# - reruns are idempotent (409/exists are skipped, never deleted)
#
# usage: ./scripts/desk-loadtest.sh [--base URL] [--users N] [--groups N]
#        [--password PW] [--prefix NAME] [--jobs N]
set -euo pipefail

BASE="http://127.0.0.1:3002"
USERS=200
N_GROUPS=10
PASSWORD="loadtest-pw-01"
PREFIX="loadtest-"
JOBS=16

while [ $# -gt 0 ]; do
  case "$1" in
    --base) BASE="$2"; shift 2 ;;
    --users) USERS="$2"; shift 2 ;;
    --groups) N_GROUPS="$2"; shift 2 ;;
    --password) PASSWORD="$2"; shift 2 ;;
    --prefix) PREFIX="$2"; shift 2 ;;
    --jobs) JOBS="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INST="$ROOT/environments/app-instances"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

pad() { printf '%s%03d' "$PREFIX" "$1"; }

# 0. preflight: server must already run (we never start/stop services here)
if ! curl -s -m 5 "$BASE/health" | grep -q '^ok$'; then
  echo "server not healthy at $BASE — start it first" >&2
  exit 1
fi
echo "== target: $BASE"

# 1. register users (parallel; 409 = already there)
register_one() {
  local u="$1" code
  code=$(curl -s -o /dev/null -w '%{http_code}' -m 30 -X POST "$BASE/auth/register" \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"$u\",\"password\":\"$PASSWORD\"}")
  case "$code" in
    201) echo "CREATED $u" ;;
    409) echo "EXISTS  $u" ;;
    *)   echo "FAIL    $u http=$code" ;;
  esac
}
echo "== phase 1: registering $USERS users (jobs=$JOBS)"
pids=()
for ((i = 1; i <= USERS; i++)); do
  u="$(pad "$i")"
  ( register_one "$u" > "$TMP/reg-$i.out" 2>&1 ) &
  pids+=($!)
  if ((${#pids[@]} >= JOBS)); then
    wait -n
    # drop finished pids (bash >=5: wait -p)
    npids=(); for p in "${pids[@]}"; do kill -0 "$p" 2>/dev/null && npids+=("$p"); done; pids=("${npids[@]}")
  fi
done
wait
created=$(grep -h '^CREATED' "$TMP"/reg-*.out 2>/dev/null | wc -l || true)
exists=$(grep -h '^EXISTS' "$TMP"/reg-*.out 2>/dev/null | wc -l || true)
fails=$(grep -h '^FAIL' "$TMP"/reg-*.out 2>/dev/null || true)
echo "   created=$created exists=$exists"
if [ -n "$fails" ]; then echo "$fails"; echo "register failures — aborting" >&2; exit 1; fi

# 2. desktop envs (fast, sequential)
echo "== phase 2: writing $USERS desktop envs under environments/app-instances/"
for ((i = 1; i <= USERS; i++)); do
  u="$(pad "$i")"
  d="$INST/desk-test-$(printf '%03d' "$i")"
  mkdir -p "$d"
  cat > "$d/config.toml" <<EOF
# synthetic desk home for $u (generated, gitignored)
server_url = "$BASE"
request_timeout_secs = 15
theme = "dark"
EOF
  cat > "$d/state.json" <<EOF
{"last_user": "$u", "active_group": null, "panel": "chat"}
EOF
  cat > "$d/SYNTHETIC" <<EOF
SYNTHETIC TEST DATA — NOT A REAL USER.
Generated by scripts/desk-loadtest.sh ($u). Never use against real data.
EOF
done
echo "   envs ready"

login_token() {
  curl -s -m 20 -X POST "$BASE/auth/login" -H 'Content-Type: application/json' \
    -d "{\"username\":\"$1\",\"password\":\"$PASSWORD\"}" \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["access_token"])'
}

# 3. groups: round-robin membership, created by user 1
echo "== phase 3: creating $N_GROUPS groups"
first="$(pad 1)"
tok="$(login_token "$first")"
for ((g = 1; g <= N_GROUPS; g++)); do
  members=""
  for ((i = 1; i <= USERS; i++)); do
    if (((i - 1) % N_GROUPS + 1 == g)); then
      members="$members\"$(pad "$i")\","
    fi
  done
  members="[${members%,}]"
  code=$(curl -s -o /dev/null -w '%{http_code}' -m 20 -X POST "$BASE/groups" \
    -H "Authorization: Bearer $tok" -H 'Content-Type: application/json' \
    -d "{\"name\":\"load-group-$g\",\"members\":$members}")
  echo "   load-group-$g -> http=$code"
done

# 4. messages: every user posts once into their round-robin group
post_one() {
  local i="$1" u g tok code
  u="$(pad "$i")"
  g=$(( (i - 1) % N_GROUPS + 1 ))
  tok="$(login_token "$u")" || { echo "FAIL login $u"; return 0; }
  # resolve group id by name
  gid=$(curl -s -m 20 "$BASE/groups" -H "Authorization: Bearer $tok" \
    | python3 -c "import json,sys; gs=json.load(sys.stdin); print(next(g['object_key'] for g in gs if g['name']=='load-group-$g'))")
  code=$(curl -s -o /dev/null -w '%{http_code}' -m 20 -X POST "$BASE/groups/$gid/messages" \
    -H "Authorization: Bearer $tok" -H 'Content-Type: application/json' \
    -d "{\"body\":\"[load] $u here\",\"content_type\":\"text/e2ee-placeholder\"}")
  echo "$u -> group $g http=$code"
}
echo "== phase 4: posting $USERS messages (jobs=$JOBS)"
pids=()
for ((i = 1; i <= USERS; i++)); do
  ( post_one "$i" > "$TMP/msg-$i.out" 2>&1 ) &
  pids+=($!)
  if ((${#pids[@]} >= JOBS)); then
    wait -n
    npids=(); for p in "${pids[@]}"; do kill -0 "$p" 2>/dev/null && npids+=("$p"); done; pids=("${npids[@]}")
  fi
done
wait
fails=$(grep -h ' http=' "$TMP"/msg-*.out 2>/dev/null | grep -v ' http=20[01]' || true)
posted=$(grep -h ' http=20[01]' "$TMP"/msg-*.out 2>/dev/null | wc -l || true)
echo "   posted=$posted"
if [ -n "$fails" ]; then echo "$fails"; echo "post failures — aborting" >&2; exit 1; fi

# 5. verify: every group timeline holds exactly its members' messages
echo "== phase 5: verifying"
tok="$(login_token "$first")"
pass=1
for ((g = 1; g <= N_GROUPS; g++)); do
  gid=$(curl -s -m 20 "$BASE/groups" -H "Authorization: Bearer $tok" \
    | python3 -c "import json,sys; gs=json.load(sys.stdin); print(next(g['object_key'] for g in gs if g['name']=='load-group-$g'))")
  n=$(curl -s -m 20 "$BASE/groups/$gid/messages?limit=200" -H "Authorization: Bearer $tok" \
    | python3 -c 'import json,sys; print(len(json.load(sys.stdin)))')
  # expected = members assigned to group g
  exp=0
  for ((i = 1; i <= USERS; i++)); do (( (i - 1) % N_GROUPS + 1 == g )) && exp=$((exp + 1)); done
  if [ "$n" = "$exp" ]; then
    echo "   load-group-$g: $n/$exp messages OK"
  else
    echo "   load-group-$g: $n/$exp MISMATCH"; pass=0
  fi
done

if [ "$pass" = 1 ]; then
  echo "PASS: $USERS users, $N_GROUPS groups, timelines verified"
else
  echo "FAIL: timeline gaps detected" >&2; exit 1
fi
