[package]
name = "sagex-varta2"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { package = "gpui-pre", version = "0.3.6" }
gpui-linux = { package = "gpui-pre-linux", version = "0.3.6", default-features = false, features = ["x11"] }
gpui-component = "0.6.6"
anyhow = "1"
# gpui = { version = "*" }
# gpui_platform = { version = "*", features = ["font-kit", "wayland", "x11"] }
